# -*-eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t);-*-

#+title: Spellcheck Configuration
#+author: Thomas Freeman
#+date: Time-stamp: <2022-07-07 17:21:25 thomas>
#+language: en_US
#+property: header-args :results silent :exports code

#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:nil html-style:t
#+options: html5-fancy:nil tex:t num:nil
#+html_doctype: xhtml-strict
#+html_container: div
#+html_content_class: content
#+keywords: Emacs
#+html_link_home: ../../index.html
#+html_link_up: ../../init.html
#+creator: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 27.1 (<a href="https://orgmode.org">Org</a> mode 9.5.2)
#+html_head: <style>#org-div-home-and-up { text-align: right; padding-right: 10pt; }</style>

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup



* Ispell

Ispell is the default spell checking tool in Emacs. In order for spellchecking to work in Windows, hunspell must be installed with the proper dictionaries. I have downloaded hunspell from ezwinports and included it in my ~~/.emacs.d/~ directory so that I can also use hunspell when I am using Emacs as a portable app from a USB drive. To use hunspell for spell checking, we must first configure the Ispell package:

#+begin_src emacs-lisp :tangle yes
  (use-package ispell
    :straight (:type built-in)
    :defer t
    :config
    (if (eq system-type 'windows-nt)
        (progn (setq ispell-program-name (expand-file-name "~/.emacs.d/hunspell/bin/hunspell.exe"))
               (setq ispell-personal-dictionary "~/.emacs.d/hunspell_en_US")
               (setq ispell-local-dictionary "en_US")
               (setq ispell-local-dictionary-alist
                     '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "en_US") nil utf-8))))
      (setq ispell-program-name (whicher "hunspell"))))
#+end_src

* Flyspell

Flyspell mode can be hooked to various buffer modes so that spell-checking can be done as typing occurs. As you type, a red wavy line will appear under text that it deems to be incorrectly spelled.

#+begin_src emacs-lisp :tangle yes
  (use-package flyspell
    :straight (:type built-in)
    :defer t
    :init
    (add-hook 'prog-mode-hook 'flyspell-prog-mode)
    (add-hook 'text-mode-hook 'flyspell-mode))
#+end_src

* End

#+begin_src emacs-lisp :tangle yes
  (provide 'freemacs-spellcheck)

  ;;; freemacs-spellcheck.el ends here
#+end_src
