;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mouse-minor-mode-menu
	org-self-insert-command
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	overwrite-mode
	wdired-next-line
	wdired-previous-line
	))
