# -*- eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t); -*-

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

#+title: Emacs Early Init
#+authgor: Thomas Freeman
#+date: Time-stamp: <2022-06-16 21:08:36 thomas>
#+description: This org-mode file contains an org-babel implementation of the .emacs or /.emacs.d/init.el file.
#+language: en
#+property: header-args :results silent :exports code
#+options: tex:t


[[file:index.html][Home]]

This file contains Emacs Lisp code that will run /before/ the Emacs [[file:init.el][init.el]] file.

This file was written using Emacs Org Mode. This makes navigating and modifying my Emacs configuration much simpler as I can place different elements of my configuration under separate headings. The code in this file is placed in source code blocks that are tangled to the ~early-init.el~ file that Emacs will look for upon starting. When this file is saved, the source code blocks that are marked for tangling will write their contents to ~early-init.el~.

* Header for early-init.el
The following code block will add a header to the ~early-init.el~ file when it is generated on saving.

#+begin_src emacs-lisp :tangle yes
  ;;; early-init.el --- Emacs early init -*- lexical-binding: t -*-
;; 

;; Author: Thomas Freeman
;; Maintainer: Thomas Freeman
;; Created: 09 Jan 2022

;; URL: https://github.com/tfree87/.emacs.d

;; This file is an early-init file for Emacs. It will be executed before
;; init.el when emacs is loaded.

;; This file IS NOT intended to be edited! It was generated by init.org.

;;; Commentary:

;; For documentation and for editing this file, see the init.org in the
;; github repository tfree87/.emacs.d
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Code:

#+end_src

* Decrease Garbage Collection Frequency

Emacs collects garbage very fequently slowing down the startup process. Emacs normally does a garbage collection every 800 kB. Since I always have the RAM for it, I have set the garbage collection to only happen after 500 MB. Increasing the number above this does not provide any significant gains in startup time as of yet. This idea came from https://blog.d46.us/advanced-emacs-startup/#/.emacs.d/init.el.

#+begin_src emacs-lisp :tangle yes
  (setq gc-cons-threshold 500000000)
#+end_src

#+begin_src emacs-lisp :tangle yes
  (require 'benchmark-init)
  (add-hook 'after-init-hook 'benchmark-init/deactivate)
#+end_src

* Prevent Unwanted Runtime Compilation

Prevent extra unnecessary runtime compilation for gccemacs. This idea came from the [[https://github.com/hlissner/doom-emacs][Doom Emacs]] ~early-init.el~ file.

#+begin_src emacs-lisp :tangle yes
  (setq native-comp-deferred-compilation nil)
#+end_src

* Disable Emacs Package Manager

In order to prevent conflicts between ~straight.el~ and the Emacs package manager, ~package-enable-at-startup~ should be set to ~nil~. This came from the [[https://github.com/raxod502/straight.el][straight.el]] installation instructions.

#+begin_src emacs-lisp :tangle yes
  (setq package-enable-at-startup nil)
#+end_src

* Reduce Redisplay

To reduce slowdowns caused by early redisplays when loading, the following code will reduce the amount of times Emacs redisplays when setting up windows. This idea came from the [[https://github.com/hlissner/doom-emacs][Doom Emacs]] ~early-init.el~ file.

#+begin_src emacs-lisp :tangle yes
  (setq-default inhibit-redisplay t
                inhibit-message t)
  (add-hook 'window-setup-hook
            (lambda ()
              (setq-default inhibit-redisplay nil
                            inhibit-message nil)
              (redisplay)))
#+end_src

* Set Environment to UTF-8

Set the default coding system to UTF-8.This idea came from the [[https://github.com/hlissner/doom-emacs][Doom Emacs]] ~early-init.el~ file.

#+begin_src emacs-lisp :tangle yes
  (set-language-environment "UTF-8")
  (setq default-input-method nil)
#+end_src

* End

#+begin_src emacs-lisp :tangle yes
  ;;; early-init.el ends here
#+end_src
