;;; init.el --- Emacs initialization file -*- lexical-binding: t -*-

;; Copyright (C) 2022-2024 Thomas Freeman

;; Author: Thomas Freeman
;; Maintainer: Thomas Freeman
;; Keywords: lisp
;; Created: 09 Jan 2022

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is an init file for Emacs.
;; This file is NOT a part of Emacs.
;; This file IS NOT intended to be edited! It was generated by init.org.
;; For code comments, see init.org.

;;; URL: https://github.com/tfree87/.emacs.d

;; For documentation and for editing this file, see the init.org in the
;; github repository tfree87/.emacs.d
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Code:

(let ((file-name-handler-alist nil))
  (let ((default-directory "~/.emacs.d/modules/"))
    (normal-top-level-add-subdirs-to-load-path))
  (defun freemacs/isportable-p ()
    "A function to check whether Emacs was executed as a portable application in Windows by the runemacs.bat script."
    (string= (getenv "EMACS_PORTABLE") "Y"))
  (when (freemacs/isportable-p)
    (add-to-list 'exec-path "~/PortableApps/GitPortable/App/Git/bin"))
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
  (require 'freemacs-elisp)
  (require 'freemacs-straight)
  (require 'freemacs-benchmark-init)
  (require 'freemacs-no-littering)
  (require 'freemacs-whicher)
  (require 'freemacs-aggressive-indent)
  (require 'freemacs-cwm)
  (require 'freemacs-autohotkey)
  (require 'freemacs-battery)
  (require 'freemacs-cape)
  (require 'freemacs-consult)
  (require 'freemacs-corfu)
  (require 'freemacs-dired)
  (require 'freemacs-drsync)
  (require 'freemacs-docker)
  (require 'freemacs-defaults)
  (require 'freemacs-eat)
  (require 'freemacs-elfeed)
  (require 'freemacs-elfeed-protocol)
  (require 'freemacs-embark)
  (require 'freemacs-eshell)
  (require 'freemacs-fireplace)
  (require 'freemacs-fotd)
  (require 'freemacs-gnus)
  (require 'freemacs-help)
  (require 'freemacs-hydra)
  (require 'freemacs-imenu)
  (require 'freemacs-graphing)
  (require 'freemacs-latex)
  (require 'freemacs-ledger)
  (require 'freemacs-listen)
  (require 'freemacs-magit)
  (require 'freemacs-marginalia)
  (require 'freemacs-markdown)
  (require 'freemacs-meow)
  (require 'freemacs-nerd-icons)
  (require 'freemacs-orderless)
  (require 'freemacs-org)
  (require 'freemacs-org-contacts)
  (require 'freemacs-org-mime)
  (require 'freemacs-org-mm)
  (require 'freemacs-org-ql)
  (require 'freemacs-orgsl)
  (require 'freemacs-ox-publish)
  (require 'freemacs-pdf)
  (require 'freemacs-recentf)
  (require 'freemacs-savehist)
  (require 'freemacs-slime)
  (require 'freemacs-trashed)
  (require 'freemacs-vertico)
  (require 'freemacs-vterm)
  (require 'freemacs-theme)
  (require 'freemacs-sp)
  (require 'freemacs-academic-writing)
  (require 'freemacs-spellcheck)
  (require 'freemacs-winner)
  (require 'freemacs-yasnippet)
  (require 'freemacs-youtube)
  (require 'freemacs-server)
  (setq gc-cons-threshold 800000))

;;; init.el ends here
