# -*-eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t);-*-
 
#+title: Emacs Configuration
#+author: Thomas Freeman
#+date: Time-stamp: <2025-01-24 18:37:14 thomas>
#+description: This org-mode file contains an org-babel implementation of the .emacs or .emacs.d/init.el file.
#+language: en_US
#+property: header-args :results silent :exports code

#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:nil html-style:t
#+options: html5-fancy:nil tex:t num:nil 
#+html_doctype: xhtml-strict
#+html_container: div
#+html_content_class: content
#+keywords: Emacs
#+html_link_home: index.html
#+html_link_up: index.html

#+SETUPFILE: https://tfree87.github.io/org-html-themes/org/theme-readtheorg.setup
-----


* About this Document

This file was written using Emacs Org Mode. This makes navigating and modifying my Emacs configuration much simpler as I can place different elements of my configuration under separate headings. The code in this file is placed in source code blocks that are tangled to the ~init.el~ file that Emacs will look for upon starting. When this file is saved, the source code blocks that are marked for tangling will write their contents to ~init.el~.

* Header for ~init.el~

The following code block will add a header to the ~init.el~ file when it is generated on saving:

#+begin_src emacs-lisp :tangle yes :noweb tangle
  ;;; init.el --- Emacs initialization file -*- lexical-binding: t -*-

  ;; Copyright (C) 2022-2024 Thomas Freeman

  ;; Author: Thomas Freeman
  ;; Maintainer: Thomas Freeman
  ;; Keywords: lisp
  ;; Created: 09 Jan 2022

  ;; This program is free software; you can redistribute it and/or modify
  ;; it under the terms of the GNU General Public License as published by
  ;; the Free Software Foundation, either version 3 of the License, or
  ;; (at your option) any later version.

  ;; This program is distributed in the hope that it will be useful,
  ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
  ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ;; GNU General Public License for more details.

  ;; You should have received a copy of the GNU General Public License
  ;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

  ;;; Commentary:

  ;; This file is an init file for Emacs.
  ;; This file is NOT a part of Emacs.
  ;; This file IS NOT intended to be edited! It was generated by init.org.
  ;; For code comments, see init.org.

  ;;; URL: https://github.com/tfree87/.emacs.d

  ;; For documentation and for editing this file, see init.org in the
  ;; github repository tfree87/.emacs.d
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; Code:

  <<emacs_init>>

  ;;; init.el ends here
#+end_src

* Performance Optimization

Reduce the load time for Emacs. See [[https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/][this Reddit post]] for more information.

#+begin_src emacs-lisp :noweb eval :noweb-ref emacs_init

  ;; Speed up Emacs loading during initialization.
  
  (let ((file-name-handler-alist nil))

    <<emacs_custom>>

    ;; Load modules from modules directory.
    ;; Correct ordering is critical, see init.org.

    <<emacs_modules>>

    ;; Set garbage collection back to normal.
    (setq gc-cons-threshold 800000))
#+end_src

* Custom Set Variables

Place custom variables in [[./custom.el]] rather than [[./init.el]] and load it.

#+begin_src emacs-lisp :noweb-ref emacs_custom
  ;; Tell Emacs where to find custom variables from the customize interface.

  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+end_src

* Load Path

Add the ~modules~ directory and all of its sub-directories to the ~load-path~.

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (let ((default-directory "~/.emacs.d/modules/"))
    (normal-top-level-add-subdirs-to-load-path))
#+end_src

* Helper Functions

Load [[./modules/general/freemacs-elisp.org][helper functions]] required for Emacs initialization. These functions don't rely on external libraries to keep loading fast.

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-elisp)
#+end_src

* Portable Emacs

If running Emacs as a portable app, configure it prior to running Straight.el so Straight can find the git executable.

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-portable)
#+end_src

* Startup Modules

Modules in this section should be run before the others.

** Benchmark Init

Use benchmark-init to check the time that it takes to load Emacs.

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-benchmark-init)
#+END_SRC

** No-littering

Load the [[./modules/startup/freemacs-no-littering.org][No Littering module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-no-littering)
#+end_src

** Whicher

Load the [[./modules/startup/freemacs-whicher.org][Whicher module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-whicher)
#+end_src

* Other Modules

** Trapt

#+begin_src emacs-lisp :tangle yes
  (require 'freemacs-trapt)
#+end_src

** Aggressive Indent

Load the [[./modules/coding/freemacs-aggressive-indent.org][Aggressive Indent module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-aggressive-indent)
#+end_src

** Centered-Window Mode

Load the [[./modules/theme/freemacs-cwm.org][Centered Window module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-cwm)
#+end_src

** AutoHotKey

Load the [[./modules/coding/freemacs-autohotkey.org][AutoHotKey module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-autohotkey)
#+end_src

** Battery

Load the [[./modules/defaults/freemacs-battery.org][Battery module]].

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-battery)
#+end_src

** Cape

Load the [[./modules/completion/freemacs-cape.org][Cape module]].

#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-cape)
#+end_src

** Consult

Load the [[./modules/completion/freemacs-consult.org][Consult module]].

#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-consult)
#+end_src

** Corfu

Load the [[./modules/completion/freemacs-corfu.org][Corfu module]]

#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-corfu)
#+end_src

** Dired

Load the [[file:modules/file-tools/freemacs-dired.org][Dired module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-dired)
#+end_src

** Dired Rsync

Load the [[./modules/file-tools/freemacs-drsync.org][Dired Rsync module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-drsync)
#+end_src

** Docker

Load the the [[file:modules/docker/freemacs-docker.org][docker module]].

#+begin_src emacs-lisp  :noweb-ref emacs_modules 
  (require 'freemacs-docker)
#+end_src

** Emacs Defaults

 Changes to the default settings of Emacs in the [[file:modules/defaults/freemacs-defaults.org][defaults module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-defaults)
#+end_src

** Eat

Load the [[./modules/shells/freemacs-eat.org][Eat Module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-eat)
#+end_src

** Elfeed

Load the [[./modules/elfeed/freemacs-elfeed.org][Elfeed Module]].
#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-elfeed)
#+end_src

** Elfeed Protocol

Load the [[./modules/elfeed/freemacs-elfeed-protocol.el][Elfeed Protocol module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-elfeed-protocol)
#+end_src   

** Embark

Load the [[./modules/completion/freemacs-embark.org][Embark module]]
#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-embark)
#+end_src

** Eshell
Load the [[./modules/shells/freemacs-eshell.org][Eshell Module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-eshell)
#+end_src

** Fireplace

Load the [[./modules/fun/freemacs-fireplace.org][Fireplace module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-fireplace)
#+end_src

** Function of the Day

Load the [[./modules/help/freemacs-fotd.org][Function of the Day module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-fotd)
#+end_src

** Gnus

Load the [[./modules/email/freemacs-gnus.org][Gnus Module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-gnus)
#+end_src

** Helpful

Load the [[./modules/help/freemacs-helpful.org][Helpful module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
   (require 'freemacs-helpful)
#+end_src

** Imenu

Load the [[./modules/defaults/freemacs-imenu.org][Imenu module]].

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-imenu)
#+end_src

** Graphing

Load the [[file:modules/graphing/freemacs-graphing.org][graphing module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-graphing)
#+end_src

** \LaTeX{}

Configuration for working with \LaTeX documents can be found in the [[file:modules/publishing/freemacs-latex.org][\LaTeX{} module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-latex)
#+end_src

** Ledger

Load the [[file:modules/math/freemacs-ledger.org][Ledger module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-ledger)
#+end_src

** Listen

Add the [[./modules/multimedia/freemacs-listen.org][Listen module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-listen)
#+end_src

** Magit

Load the [[./modules/coding/freemacs-magit.org][Magit module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-magit)
#+end_src

** Marginalia

Load the [[./modules/completion/freemacs-marginalia.org][Marginalia module]].

#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-marginalia)
#+end_src

** Markdown

Load the [[File:modules/publishing/freemacs-markdown.org][Markdown module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-markdown)
#+end_src

** Meow Mode

Load the [[./modules/editing/freemacs-meow.org][Meow Mode module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-meow)
#+end_src

** Mixed Pitch Mode

Load the [[./modules/theme/freemacs-mp.org][Mixed Pitch module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-mp)
#+end_src

** Nerd Icons

Load the [[./modules/theme/freemacs-nerd-icons.org][Nerd Icons module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-nerd-icons)
#+end_src

** Nyan Mode

Load the [[./modules/theme/freemacs-nyan.org][Nyan module]].

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-nyan)
#+end_src

** Orderless

Load the [[./modules/completion/freemacs-orderless.el][Orderless module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-orderless)
#+end_src

** Org

Load the [[./modules/org/freemacs-org.org][Org Mode module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-org)
#+end_src

** Org Contacts

Load the [[./modules/org/freemacs-org-contacts.org][Org Contacts module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-org-contacts)
#+end_src

** Org Mime

Load the [[./modules/email/freemacs-org-mime.org][Org MIME module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-org-mime)
#+end_src

** Org Mind Map

Load the [[./modules/org/freemacs-org-mm.org][Org Mind Map module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-org-mm)
#+end_src

** Org-QL

Load the [[./modules/org/freemacs-org-ql.org][Org Ql module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-org-ql)
#+end_src

** Org Super Links

Load the [[./modules/org/freemacs-orgsl.org][Org Super Links module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-orgsl)
#+end_src

** Ox-publish

Load the [[file:modules/publishing/freemacs-ox-publish.org][ox-publish module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-ox-publish)
#+end_src

** PDF-Tools

Load the [[./modules/publishing/freemacs-pdf.org][PDF module]].
#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-pdf)
#+end_src

** Popper

Load the [[./modules/help/freemacs-popper.org][Popper module]].

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-popper)
#+end_src

** Recentf

Load the [[./modules/session/freemacs-recentf.org][Recentf module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-recentf)
#+end_src

** Repeat Help

Load the [[./modules/help/freemacs-rh.org][Repeat Help module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-rh)
#+end_src

** Savehist

Load the [[./modules/session/freemacs-savehist.org][Savehist module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-savehist)
#+end_src

** Sly

Load the [[./modules/coding/freemacs-sly.org][Sly module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-sly)
#+end_src

** Trashed

Load the [[./modules/file-tools/freemacs-trashed.org][Trashed Module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-trashed)
#+end_src

** Vertico

Load the [[file:modules/completion/freemacs-completion.org][completion module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
    (require 'freemacs-vertico)
#+end_src

** VTerm

Load the [[./modules/shells/freemacs-vterm.org][Vterm module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-vterm)
#+end_src

** Theme style

Load the [[./modules/theme/freemacs-theme.org][Theme module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
    (require 'freemacs-theme)
#+end_src

** Spacious Padding

Load the [[./modules/theme/freemacs-sp.org][Spacious Padding module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-sp)
#+end_src

** Academic Writing

Load the [[file:modules/publishing/freemacs-academic-writing.org][academic writing module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-academic-writing)
#+end_src

** Spellchecking

Load the [[./modules/publishing/freemacs-spellcheck.org][Spellcheck module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-spellcheck)
#+end_src

** Which Key

Load the [[./modules/help/freemacs-wk.org][Whick Key module]].

#+begin_src elisp :noweb-ref emacs_modules
  (require 'freemacs-wk)
#+end_src

** Winner

Load the [[./modules/session/freemacs-winner.org][Winner module]].

#+begin_src elisp :noweb-ref emacs_modules 
(require 'freemacs-winner)
#+end_src

** YASnippet

Load the [[./modules/editing/freemacs-yasnippet.org][YASnippet module]].

#+begin_src emacs-lisp  :noweb-ref emacs_modules
  (require 'freemacs-yasnippet)
#+end_src

** YouTube

Load the [[./modules/youtube/freemacs-youtube.org][YouTube module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules 
  (require 'freemacs-youtube)
#+end_src

** Emacs Server

Load the [[file:modules/server/freemacs-server.org][server module]].

#+begin_src emacs-lisp :noweb-ref emacs_modules
  (require 'freemacs-server)
#+end_src

