# -*-eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t);-*-

#+title: Theme Configuration
#+author: Thomas Freeman
#+date: Time-stamp: <2025-01-05 13:55:34 thomas>
#+language: en_US
#+property: header-args :results silent :exports code

#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:nil html-style:t
#+options: html5-fancy:nil tex:t num:nil toc:t
#+html_doctype: xhtml-strict
#+html_container: div
#+html_content_class: content
#+keywords: Emacs
#+html_link_home: ../../index.html
#+html_link_up: ../../init.html
#+creator: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 27.1 (<a href="https://orgmode.org">Org</a> mode 9.5.2)
#+html_head: <style>#org-div-home-and-up { text-align: right; padding-right: 10pt; }</style>

#+SETUPFILE: https://tfree87.github.io/org-html-themes/org/theme-readtheorg.setup
-----


* Custom Faces

This section contains custom set faces.

** Change Calfw Grid Color

When using Calfw, the default grid color does not show very well when using the Droom theme ~doom-outrun-electric~. The following will change it to a color that will be easier to see.

#+begin_src emacs-lisp
  (custom-theme-set-faces
   'user
    '(cfw:face-grid ((t (:foreground "magenta")))))
#+end_src

** Default Font

Change the default font to use Hack if it is available.

#+begin_src emacs-lisp :tangle yes :comments org
  (when (font-available-p "Hack")
    (custom-theme-set-faces
     'user
     '(default ((t (:family "Hack" :foundry "outline" :slant normal :weight normal :height 100 :width normal))))))
#+end_src

* Doom Themes

Set the theme to ~doom-outrun-electric~.

#+begin_src emacs-lisp :tangle yes
  (use-package doom-themes
    :straight t
    :if window-system
    :defer 1
    :config
    (load-theme 'doom-outrun-electric t)
    (doom-themes-org-config))
#+end_src

* Doom Modeline

The Doom Modeline decorates the modeline with icons and cleans up much of the clutter in the modeline.

#+begin_src emacs-lisp :tangle yes
  (use-package doom-modeline
    :straight t
    :if window-system
    :defer 1
    :config (doom-modeline-mode))
#+end_src

* Menu Bar, Scroll Bar, and Tool Bar

Hide the menu bar.

#+begin_src emacs-lisp :tangle yes
  (use-package menu-bar
    :straight (:type built-in)
    :config
    (menu-bar-mode -1))
#+end_src

Hide the tool bar.
#+begin_src emacs-lisp :tangle yes :comments org
  (use-package tool-bar
    :straight (:type built-in)
    :config
    (tool-bar-mode -1))
#+end_src

Hide the scroll bar.
#+begin_src emacs-lisp :tangle yes :comments org
  (use-package scroll-bar
    :straight (:type built-in)
    :config
    (toggle-scroll-bar -1))
#+end_src

* Nyan Mode

[[https://github.com/TeMPOraL/nyan-mode][Nyan-mode]] displays a nyan cat on the mode line. The length of the rainbow corresponds to buffer location.

#+begin_src emacs-lisp :tangle yes
  (use-package nyan-mode
    :straight t
    :if window-system
    :defer 3
    :init
    ;; Requires mplayer to play the music
    (whicher "mplayer")
    :custom
    (nyan-wavy-trail t)
    :config
    (nyan-mode)
    (nyan-start-animation))
#+end_src

* End

Tell Emacs what package this file provides.
#+begin_src emacs-lisp :tangle yes :comments org
  (provide 'freemacs-theme)

  ;;; freemacs-theme.el ends here
#+end_src
