#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:nil html-style:t
#+options: html5-fancy:nil tex:t
#+html_doctype: xhtml-strict
#+html_container: div
#+html_content_class: content
#+description:
#+keywords:
#+html_link_home:
#+html_link_up:
#+html_mathjax:
#+html_equation_reference_format: \eqref{%s}
#+html_head:
#+html_head_extra:
#+subtitle:
#+infojs_opt:
#+creator: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 27.1 (<a href="https://orgmode.org">Org</a> mode 9.5.2)
#+latex_header:

#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Another Emacs Configuration
#+date: <2022-03-30 Wed>
#+author: Thomas Freeman
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.5.2)
#+cite_export:


* Welcome

Welcome to the Github page for my Emacs configuration. I have created this Github pages site to help provide a place where I can post all of the custom modifications I have made to make Emacs as productive as possible for me. While Emacs has excellent documentation, and I highly recommend reading it, there is so much in the Emacs ecosystem that it doesn't even begin to cover much of the excellent third-party packages that have been released to extend Emacs. This is why I have decided that I would post my own Emacs configuration for anyone else who wants to learn by example. I have certainly found a lot of inspiration in scouring the internet for Emacs configurations created by other users.

* About My Emacs Setup

I have tried to make an Emacs setup that is flexible for use in multiple contexts. While I prefer to use libre operating systems. I often find that for work I am limited to using a Windows system. As I have learned to rely on the powerful features of Emacs for much of the computing that I do, I have found a way to replicate the functions I love on Emacs as a portable system by running Emacs on a USB flash drive alongside the PortableApps platform. This allows me to take my Emacs setup everywhere I go. Here are some features of my setup:
1. Portable
   - A file, runemacs.bat, will call the Emacs executable on the USB flash drive and set the home directory to the drive label of the flash drive.
   - Emacs will check to see if it is being called as a portable app and can call on portable libraries such as MikTeX portable and Git portable to restore lost functionality.
   - The Emacs configuration can be pulled from Github and uses straight.el to pull install all Emacs packages.
2. Fast Loading
   - Package loading is deferred with use-package when possible
   - Designed to load quickly on older computers and from a flash drives
3. Multi-platform
   - This configuration has been tested on:
     + Linux Mint
     + Windows using Chocolatey to install dependencies
     + Windows as a USB PortableApp with dependencies installed on the USB drive as PortableApps
4. Emacs Server
   - Starts an Emacs server so that other Emacs frames can be opened quickly and access the same buffers by running an ~emacsclient~ instance.

* Browse The Configuration

If you want to browse my Emacs configuration, there are a couple ways to do it.

** With Documentation/Commentary
I have used Org Mode to program my ~init.el~ file with my annotations, documentation, explanations, and links to source code and sites where I borrowed my code from.

- [[file:init.html][Init.html]] :: Browse the code along with my commentary exported to HTML from my ~init.org~ file.
- [[https://github.com/tfree87/.emacs.d/blob/main/init.org][init.org on Github]] : Read the ~init.org~ file directly in

** Without Documentation/Commentary
You can also checkout the files directly on Github if you are not interested in sifting through all the extra text and just want to take a look at the raw code.

- [[https://github.com/tfree87/.emacs.d/blob/main/custom.el][custom.el]] :: Customizations set by the Emacs ~M-x customize~ interface
- [[https://github.com/tfree87/.emacs.d/blob/main/early-init.el][early-init.el]] :: A file that is loaded before ~init.el~
- [[https://github.com/tfree87/.emacs.d/blob/main/gnus.el][gnus.el]] :: My Gnus newsreader/email setup (I only use Gnus for reading email)
- [[https://github.com/tfree87/.emacs.d/blob/main/init.el][init.el]] :: The standard Emacs init file
- [[https://github.com/tfree87/.emacs.d/blob/main/runemacs.bat][runemacs.bat]] :: A Windows batch file to set up the environment for running Emacs as a portable application 
