# -*-eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t);-*-

#+title: Org Mode Configuration
#+author: Thomas Freeman
#+date: Time-stamp: <2024-12-09 21:19:04 thomas>
#+language: en_US
#+property: header-args :results silent :exports code

#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:nil html-style:t
#+options: html5-fancy:nil tex:t num:nil toc:t
#+html_doctype: xhtml-strict
#+html_container: div
#+html_content_class: content
#+keywords: Emacs
#+html_link_home: ../../index.html
#+html_link_up: ../../init.html
#+creator: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 27.1 (<a href="https://orgmode.org">Org</a> mode 9.5.2)
#+html_head: <style>#org-div-home-and-up { text-align: right; padding-right: 10pt; }</style>

-----


* Configure Org

Set up configuration for buit-in Org Mode.  
#+begin_src emacs-lisp :comments org :tangle yes :noweb yes
  (use-package org
    :straight (:type built-in)
    :defer t
    :init
    <<org_init>>
    (whicher "pdflatex")
    (whicher "biber")
    :bind
    ("C-c l" . #'org-store-link)
    ("C-c a" . #'org-agenda)
    ("C-c c" . #'org-capture)
    :custom
    <<org_customize>>
    :config
    (add-hook 'org-mode-hook #'turn-on-flyspell)
    <<org_config>>
    <<babel_languages>>
    (load-file "~/.emacs.d/org-templates/capture-templates.el"))

  (use-package org-contrib
    :straight t
    :defer t
    :config
    <<org_contrib_config>>)
#+end_src

** Use Unique IDs for Org Links

Create unique IDs for every internal link between Org headings to prevent links from breaking when files or headings are restructured.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
#+end_src

** Directories

Set up the default directories for Org Mode.

*** Default Directory

Tell org-mode which directory is the default directory for all org-mode files.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-directory "~/org")
#+end_src

*** Location of Agenda Files

Tell org-mode in which directory all the agenda files can be found.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-agenda-start-on-weekday nil)
  (org-agenda-files `("~/org/agenda"))
#+end_src

** Filing Notes

*** Default Notes File

Tell org mode where the default notes file can be found for org-capture.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-default-notes-file (concat org-directory "/notes/notes.org"))
#+end_src

*** Refile Targets

**** Set Org Files for Refiling

In order to refile/move tasks from the inbox to other agenda files and subtrees, the following must be set:
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
    (org-ref~ile-targets '((org-agenda-files :maxlevel . 4)
                            ((concat org-directory "/notes") :maxlevel . 3)))
#+end_src

**** Allow Refile as Top-level Heading

Allow for refiling org-mode tasks at the top of a file.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-refile-use-outline-path 'file)
  (org-outline-path-complete-in-steps nil)
#+end_src

Setting this variable allows for refiling tasks under a new heading on the fly.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-refile-allow-creating-parent-nodes 'confirm)
#+end_src

** Exporting

To remove headers labeled with the ~:ignore:~ tag, the following needs to be implemented:
#+begin_src emacs-lisp :comments org :noweb-ref org_contrib_config
  (require 'ox-extra)
  (ox-extras-activate '(ignore-headlines))
#+end_src

So that exporting Org Mode buffers doesn't lock up Emacs, the option ~org-export-in-background~ can be set to a non-nil value.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-export-in-background t)
#+end_src

** Task Management Customization

*** Drawer for State Changes

Put changes of TODO states for org-mode into a drawer under each heading so that it does not conflict with content under the headings.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-log-into-drawer t)
#+end_src

*** Custom TODO Keywords

Set up the sequence of org-todo task keywords to allow for delegated (WAITING) tasks and CANCELED tasks.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-todo-keywords
   '((sequence "TODO(t)"
               "WAITING(w)"
               "|"
               "DONE(d)"
               "CANCELED(c)")
     (sequence "MAYBE(m)"
               "SOMEDAY(s)"
               "PLANNING(p)"
               "|"
               "PLANNED(P)")
     (sequence "SCRIPTING(S)"
               "TESTING(G)"
               "REVIEW(R)"
               "APPROVAL(A)"
               "|"
               "EFFECTIVE(E)")))
#+end_src

*** Project Tags

Changing this setting prevents these tag from being inherited by subheadings.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-tags-exclude-from-inheritance '("project"))
#+end_src

*** Stuck Projects

Define a stuck project as any headline with the project keyword which has no TODO item below it.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-stuck-projects
   '("+project/-MAYBE-DONE"
     ("NEXT" "TODO")
     nil
     "\\<IGNORE\\>"))
#+end_src

** BibLaTeX in Org-mode

In order to get BibLaTeX to operate in org-mode, the ~org-latex-pdf-process~ variable needs to be changed to reflect this.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-latex-pdf-process
   '("pdflatex -interaction nonstopmode -output-directory %o %f"
     "biber %b"
     "pdflatex -interaction nonstopmode -output-directory %o %f"
     "pdflatex -interaction nonstopmode -output-directory %o %f"))
#+end_src

** Org-babel Languages

Activate languages to use in Org Babel
#+name: babel_languages
#+begin_src emacs-lisp :comments org
  (with-eval-after-load "org"
    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml)))
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((awk . t)
     (C . t)
     (calc . t)
     (css . t)
     (dot . t)
     (emacs-lisp . t)
     (eshell . t)
     (gnuplot . t)
     (java . t)
     (latex . t)
     (ledger . t)
     (octave . t)
     (plantuml . t)
     (python . t)
     (R . t)
     (scheme . t)
     (sed . t)
     (shell . t)
     (sql . t)
     (sqlite . t)))
#+end_src

** Appearance

This section contains modifications to how Org Mode appears in buffers.

*** Hide Emphasis Characters

Hiding emphasis characters  in Org Mode makes the text easier to read when it is being displayed directly in Emacs. This will make *bold*, /italic/, _underlined_, ~code~, and =verbatim= text show up without the *,/, _, ~, and = characters around them.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-hide-emphasis-markers t)
#+end_src

*** Word Wrapping

Turning on ~visual-line-mode~ allows the text to flow in Org Mode at the end of the window.
#+begin_src emacs-lisp :comments org :noweb-ref org_config
  (add-hook 'org-mode-hook 'visual-line-mode)
#+end_src

*** Single Space Between Headline and Tags

Just add a single space between a headline and tags for simplicity.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-tags-column 0)
#+end_src

*** Use "Clean View"

Start all Emacs org-mode buffers with "clean-view" turned on and hide.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-startup-indented t)
#+end_src

*** Native Tabs

This will allow for source code blocks in emacs org-mode to be internally indented as they would normally be in their majors modes.
#+begin_src emacs-lisp :comments org :noweb-ref org_customize
  (org-src-tab-acts-natively t)
 #+end_src

* Org Modules

Load Org modules for extra functionality.
#+begin_src emacs-lisp :noweb-ref org_customize
  (org-modules '(ol-bbdb
                 ol-bibtex
                 ol-docviewol-doi
                 ol-eww
                 ol-gnus
                 org-habit
                 org-id
                 ol-info
                 org-inlinetask
                 ol-mhe
                 org-mouse
                 org-protocol
                 ol-rmail
                 ol-w3m
                 ol-eshell
                 org-annotate-file
                 ol-bookmark
                 org-checklist
                 org-choose
                 ol-eisp-symbol
                 org-notify org-toc))
#+end_src

* Org Header Sizes

The following custom function will change the heading sizes in Org Mode to make it easier to see the different heading levels. In addition, this will also increase the size of the document title and make it more prominent. This code is modified and from [[https://github.com/daviwil][@daviwil]] from [[https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-05.org#improving-the-look][this link]].
#+begin_src emacs-lisp :comments org :tangle yes
  (defun freemacs/org-header-formatting ()
    "Change the size of headers and titles in Org Mode buffers."
    (interactive)
    (with-eval-after-load 'org
      (dolist
          (face
           '((org-level-1 . 2.00)
             (org-level-2 . 1.75)
             (org-level-3 . 1.50)
             (org-level-4 . 1.25)
             (org-level-5 . 1.10)
             (org-level-6 . 1.10)
             (org-level-7 . 1.10)
             (org-level-8 . 1.10)
             (org-document-title . 2.25)))
        (set-face-attribute (car face) nil :height (cdr face)))))
#+end_src

* End

Tell Emacs what feature this file provides.
#+begin_src emacs-lisp :comments org :tangle yes
  (provide 'freemacs-org)

  ;;; freemacs-org.el ends here
#+end_src
